data:
  problem_statements:
    path: data/problem_statements.xlsx
    sheet: Worksheet

  innovation_process:
    path: data/crieya_innovation_process.xlsx
    sheet: template

  crieya_preincubation_hub:
    path: data/crieya_preincubation_hub.txt
  
  crieya_focus:
    path: data/crieya_focus.txt

  trl_levels:
    path: data/trl_levels.txt

model:
  name: sarvam-105b